version: "3.9"

services:
  discord:
    image: thumbnailed.discord
    build:
      context: .
      dockerfile: apps/discord/Dockerfile
      target: deploy
    volumes:
      - ./apps/discord:/app
      - /app/node_modules
  web:
    image: thumbnailed.web
    build:
      context: .
      dockerfile: apps/web/Dockerfile
      target: deploy
    volumes:
      - ./apps/web:/app
      - /app/node_modules