name: '🚀 Release'
on:
  release:
    types: [published]
jobs:
  release:
    name: '🚀 Release'
    runs-on: ubuntu-latest
    steps:
      - name: '📚 Checkout'
        uses: actions/checkout@v2.3.4
      - name: '🟢 Node'
        uses: actions/setup-node@v2.1.4
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org/
      - name: '📦 Install Dependencies'
        run: npm ci
      - name: '🧪 Run Tests'
        run: npm run test
      - name: '🚀 Publish to NPM'
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}
